// Generated by `supabase gen types typescript --linked` would land here.
// Types are duplicated by hand for this scaffold so the codebase compiles
// before `supabase link` has been run.

export type UserRole = 'owner' | 'friend';
export type RelationStatus = 'pending' | 'active' | 'blocked';
export type EntryKind = 'expense' | 'lend' | 'borrow';
export type EntryStatus = 'open' | 'partially_settled' | 'settled' | 'disputed';

export interface Profile {
  id: string;
  telegram_id: number;
  telegram_username: string | null;
  first_name: string;
  last_name: string | null;
  photo_url: string | null;
  role: UserRole;
  locale: 'en' | 'bn';
  default_currency: string;
  created_at: string;
  updated_at: string;
}

export interface Relation {
  id: string;
  owner_id: string;
  friend_id: string;
  status: RelationStatus;
  invite_token: string;
  invited_at: string;
  accepted_at: string | null;
}

export interface Entry {
  id: string;
  owner_id: string;
  counterparty_id: string | null;
  relation_id: string | null;
  kind: EntryKind;
  status: EntryStatus;
  amount_cents: number;
  currency: string;
  amount_bdt_cents: number | null;
  occurred_at: string;
  memo: string;
  source: 'web' | 'telegram' | 'telegram_voice';
  source_message_id: string | null;
  raw_transcript: string | null;
  confirmed_by_owner: boolean;
  created_at: string;
  updated_at: string;
}

export interface Settlement {
  id: string;
  entry_id: string;
  amount_cents: number;
  settled_at: string;
  note: string;
  source: 'web' | 'telegram' | 'telegram_voice';
  created_at: string;
}

export interface AuditEvent {
  id: string;
  actor_id: string | null;
  event:
    | 'entry.created' | 'entry.updated' | 'entry.deleted'
    | 'entry.settled' | 'relation.invited' | 'relation.accepted' | 'relation.blocked'
    | 'auth.login' | 'auth.logout';
  subject_id: string | null;
  payload: Record<string, unknown>;
  created_at: string;
}

export interface Balance {
  owner_id: string;
  counterparty_id: string;
  net_cents: number;
  currency: string;
}

// =====================================================
// TOUR TYPES
// =====================================================

export type TourStatus = 'planning' | 'active' | 'closed';
export type TourRole = 'leader' | 'member';

export interface Tour {
  id: string;
  owner_id: string;
  name: string;
  nickname: string | null;
  destination: string | null;
  status: TourStatus;
  currency: string;
  pot_cents: number;
  starts_at: string;
  ends_at: string | null;
  notes: string;
  created_at: string;
  updated_at: string;
}

export interface TourMember {
  id: string;
  tour_id: string;
  profile_id: string;
  role: TourRole;
  allocated_cents: number;
  joined_at: string;
  exited_at: string | null;
}

export interface TourTopup {
  id: string;
  tour_id: string;
  amount_cents: number;
  source: 'web' | 'telegram' | 'telegram_voice';
  memo: string;
  occurred_at: string;
  created_at: string;
}

export interface TourSummary {
  tour_id: string;
  owner_id: string;
  name: string;
  nickname: string | null;
  destination: string | null;
  currency: string;
  status: TourStatus;
  total_pot_cents: number;
  spent_cents: number;
  repaid_cents: number;
  leftover_cents: number;
}

export interface TourMemberSummary {
  tour_id: string;
  profile_id: string;
  role: TourRole;
  allocated_cents: number;
  consumed_cents: number;
  leftover_to_member_cents: number;
}
